name: lookma
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - anyio==4.12.0
      - chumpy==0.70
      - contourpy==1.3.2
      - filelock==3.20.0
      - freetype-py==2.5.1
      - fsspec==2025.12.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - imageio==2.37.2
      - jinja2==3.1.6
      - lookma==0.1
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pyglet==2.1.11
      - pyopengl==3.1.0
      - pyrender==0.1.45
      - pyyaml==6.0.3
      - safetensors==0.7.0
      - scipy==1.15.3
      - shellingham==1.5.4
      - smplx==0.1.28
      - sympy==1.14.0
      - timm==1.0.22
      - torch==2.9.1+cu128
      - torchaudio==2.9.1+cu128
      - torchvision==0.24.1+cu128
      - tqdm==4.67.1
      - trimesh==4.10.1
      - typer-slim==0.20.1
      - typing-extensions==4.15.0
prefix: C:\Users\Jordan\miniconda3\envs\lookma
